.\scripts\start-kb-sync.ps1 `
    -Easy `
    -NoRead `
    -Version "0.1.1" `
    -CommitChanges `
    -StageAll `
    -CommitSubject "feat: advance internal QA backend MVP" `
    -RefKb "context/project_index.md" `
    -UpdatedKb "QAService + retrieval + streaming + indexing pipeline" `
    -KbCommitSubject "docs: sync internal QA backend MVP from main" `
    -KbUpdated "project_index + current_phase + repo_map + QA backend notes"