services:
  elasticsearch:
    build:
      context: ./docker/elasticsearch
    image: orionstack-elasticsearch:8.17.0-ik
    container_name: orionstack-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
  odoo:
    image: odoo:19.0
    container_name: odoo
    restart: unless-stopped
    ports:
      - "8069:8069"
    environment:
      HOST: host.docker.internal
      PORT: 5432
      USER: odoo
      PASSWORD: qq3938332
    volumes:
      - odoo-data:/var/lib/odoo

volumes:
  es_data:
  odoo-data: